[package]
name = "seismicbft-node"
version.workspace = true
edition.workspace = true

[dependencies]
seismicbft-syncer.workspace = true
seismicbft-types.workspace = true
seismicbft-application.workspace = true

commonware-broadcast.workspace = true
commonware-codec.workspace = true
commonware-consensus.workspace = true
commonware-cryptography.workspace = true
commonware-p2p.workspace = true
commonware-runtime.workspace = true
commonware-utils.workspace = true

anyhow.workspace = true
futures.workspace = true
governor.workspace = true
rand.workspace = true
tracing.workspace = true
clap.workspace = true
dirs = "6.0.0"

# testnet bin deps 
alloy-node-bindings = "1.0.9"
alloy-signer = "1.0.9"
alloy-signer-local = "1.0.9"
alloy-network = "1.0.9"
alloy-primitives = "1.2.0"
alloy-rpc-types = "1.0.9"

ethereum_ssz = "0.9.0"
serde_json = "1.0.140"

# for prom
prometheus = { version = "0.14", optional = true }
reth-metrics = { git = "https://github.com/SeismicSystems/seismic-reth.git", branch = "seismic", optional = true }
metrics = { version = "0.24.0", optional = true }
metrics-exporter-prometheus = { version = "0.16.0", default-features = false, optional = true }
metrics-process = { version = "2.1.0", optional = true }
metrics-util = { default-features = false, version = "0.19.0", optional = true }
jsonrpsee-server = { version = "0.25.1", optional = true }
http = { version = "1.0", optional = true }
eyre = { version = "0.6", optional = true }
[target.'cfg(unix)'.dependencies]
tikv-jemalloc-ctl = { version = "0.6", optional = true, features = ["stats"] }
[target.'cfg(target_os = "linux")'.dependencies]
procfs = { version = "0.17.0", optional = true }
tokio = { version = "1.45.1", features = ["full", "rt-multi-thread", "time"], optional = true }
tower = { version = "0.5.2", optional = true }


[features]
prom = ["prometheus", "reth-metrics", "metrics",
    "metrics-exporter-prometheus", "metrics-process", "metrics-util",
    "jsonrpsee-server", "http", "eyre", "procfs", "tokio", "tower"]
jemalloc = ["dep:tikv-jemalloc-ctl"]